<a href="https://colab.research.google.com/github/r00tek/data-science-bootcamp/blob/main/01-Wprowadzenie-01_numpy_intrp.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

In [195]:
x=np.array([1,3])

In [196]:
x=np.array([[1,3], [-3,1]])

In [197]:
x

array([[ 1,  3],
       [-3,  1]])

In [198]:
x.ndim

2

In [199]:

x.shape

(2, 2)

In [200]:
x=np.array([[1,2,4],[4,2,1]])

In [201]:
x.shape

(2, 3)

In [202]:
x=np.array([[[4,3,1],
           [3,1,2]],

           [[4,1,3],
           [4,2,1]],

            [[3,2,1],
             [4,3,2]]])

In [203]:
x

array([[[4, 3, 1],
        [3, 1, 2]],

       [[4, 1, 3],
        [4, 2, 1]],

       [[3, 2, 1],
        [4, 3, 2]]])

In [204]:
x.ndim

3

In [205]:
x.shape

(3, 2, 3)

In [206]:
np.zeros(shape=(4,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [207]:
 np.ones(shape=(5,5),dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [208]:
np.full(shape=(3,3),fill_value=4,dtype=int)

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

In [209]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [210]:
np.arange(start=10, stop=100, step=10)


array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [211]:
np.linspace(start=0, stop=1, num=11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [212]:
a=np.arange(15)

In [213]:
a.reshape((3,5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [214]:
a.reshape((5,-1))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [215]:
a.reshape((-1,3))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [216]:
A = np.array([3, 1, 4, 2])
B = np.array([3, -1, 3, 2])
print(A)
print(B)


[3 1 4 2]
[ 3 -1  3  2]


In [217]:
A+B

array([6, 0, 7, 4])

In [218]:
np.add(A,B)

array([6, 0, 7, 4])

In [219]:
A-B

array([0, 2, 1, 0])

In [220]:
np.subtract(A,B)

array([0, 2, 1, 0])

In [221]:
A*B

array([ 9, -1, 12,  4])

In [222]:
np.multiply(A,B)

array([ 9, -1, 12,  4])

In [223]:
A/B

array([ 1.        , -1.        ,  1.33333333,  1.        ])

In [224]:
np.divide(A,B)

array([ 1.        , -1.        ,  1.33333333,  1.        ])

In [225]:
A+3

array([6, 4, 7, 5])

In [226]:
2*A

array([6, 2, 8, 4])

In [227]:
abs(B)

array([3, 1, 3, 2])

In [228]:
x=np.array([[1,3],[-2,0]])

In [229]:
y=np.array([[6,0],[-1,2]])

In [230]:
print(x,'\n')
print(y)

[[ 1  3]
 [-2  0]] 

[[ 6  0]
 [-1  2]]


In [231]:
x*y

array([[6, 0],
       [2, 0]])

In [232]:
np.dot(x,y)

array([[  3,   6],
       [-12,   0]])

In [233]:
x.dot(y)

array([[  3,   6],
       [-12,   0]])

In [234]:
y.dot(x)

array([[ 6, 18],
       [-5, -3]])

In [235]:
x@y

array([[  3,   6],
       [-12,   0]])

In [236]:
np.random.seed(0)

In [237]:
np.random.randn()

1.764052345967664

In [238]:
np.random.randn(10)


array([ 0.40015721,  0.97873798,  2.2408932 ,  1.86755799, -0.97727788,
        0.95008842, -0.15135721, -0.10321885,  0.4105985 ,  0.14404357])

In [239]:
np.random.randn(10,4)

array([[ 1.45427351,  0.76103773,  0.12167502,  0.44386323],
       [ 0.33367433,  1.49407907, -0.20515826,  0.3130677 ],
       [-0.85409574, -2.55298982,  0.6536186 ,  0.8644362 ],
       [-0.74216502,  2.26975462, -1.45436567,  0.04575852],
       [-0.18718385,  1.53277921,  1.46935877,  0.15494743],
       [ 0.37816252, -0.88778575, -1.98079647, -0.34791215],
       [ 0.15634897,  1.23029068,  1.20237985, -0.38732682],
       [-0.30230275, -1.04855297, -1.42001794, -1.70627019],
       [ 1.9507754 , -0.50965218, -0.4380743 , -1.25279536],
       [ 0.77749036, -1.61389785, -0.21274028, -0.89546656]])

In [241]:
np.random.rand()

0.3687251706609641

In [243]:
np.random.rand(10,2)

array([[0.28280696, 0.12019656],
       [0.2961402 , 0.11872772],
       [0.31798318, 0.41426299],
       [0.0641475 , 0.69247212],
       [0.56660145, 0.26538949],
       [0.52324805, 0.09394051],
       [0.5759465 , 0.9292962 ],
       [0.31856895, 0.66741038],
       [0.13179786, 0.7163272 ],
       [0.28940609, 0.18319136]])

In [245]:
np.random.randint(10)

8

In [247]:
np.random.randint(low=10, high=101, size=16)

array([87, 40, 34, 12, 13, 23, 50, 82, 29, 82, 36, 76, 62, 77, 71, 24])

In [255]:
np.random.choice([4,2,1,4])

np.int64(1)

In [256]:
data=np.arange(10)

In [257]:
np.random.shuffle(data)

In [258]:
data

array([2, 4, 3, 6, 1, 5, 7, 0, 8, 9])

In [259]:
np.exp(1)

np.float64(2.718281828459045)

In [262]:
np.all([2,3,-1])

np.True_

In [264]:
np.any([1,2,1])

np.True_

In [271]:
a=np.random.randn(5)

In [272]:
a

array([-0.24107359,  0.05334491,  1.03081595, -1.27698899,  0.83771977])

In [273]:
np.argmax(a)

np.int64(2)

In [275]:
np.argmin(a)

np.int64(3)

In [274]:
a[np.argmax(a)]

np.float64(1.030815947669532)

In [276]:
np.argsort(a)

array([3, 0, 1, 4, 2])

In [277]:
np.max(a)

np.float64(1.030815947669532)

In [278]:
np.mean(a)

np.float64(0.08076360846958755)

In [279]:
np.median(a)

np.float64(0.05334490701920273)

In [5]:
a=np.arange(20)

In [6]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [290]:
a[3:7]

array([3, 4, 5, 6])

In [291]:
a[[0,2]]

array([0, 2])

In [7]:
a[-4:]

array([16, 17, 18, 19])

In [8]:
a=a.reshape(4,5)

In [9]:
a[2]

array([10, 11, 12, 13, 14])

In [304]:
a[:,-1]

array([ 4,  9, 14, 19])

In [10]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [11]:
a[1,2] = 14

In [12]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [13]:
for row in a:
  print(row)

[0 1 2 3 4]
[ 5  6 14  8  9]
[10 11 12 13 14]
[15 16 17 18 19]


In [16]:
for row in a:
  print(row[0:3])

[0 1 2]
[ 5  6 14]
[10 11 12]
[15 16 17]


In [21]:
a.reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6, 14],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [27]:
a.ravel()

array([ 0,  1,  2,  3,  4,  5,  6, 14,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [28]:
a.T


array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2, 14, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

In [43]:
a=np.arange(-10,10,0.5)

In [44]:
a=a.reshape(10,-1)

In [45]:
a>0

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [46]:
np.bitwise_and(a>-5, a<5)

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [47]:
np.bitwise_or(a<-5,a>5)

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])